[package]
name = "streamers_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.8"
iced_native = "0.9.0"
iced_lazy = "0.5.0"
iced_wgpu = "0.9.0"
